### ISSUE TITLE
Compilation errors with v1.7.1

### ISSUE THREAD

**Issue by vnastasi** [Tealium/tealium-kotlin#251]
Hello everyone

We're experiencing compile errors after updating `com.tealium:kotlin-core` from 1.7.0 to 1.7.1.

Here is the existing code snippet that creates a `TealiumConfig` instance (much like is described in the documentation):

```kotlin
private fun createConfiguration(
    application: Application,
    profileName: String,
    environment: Environment,
    dataSourceId: String
): TealiumConfig =
    TealiumConfig(
        application = application,
        accountName = ACCOUNT_NAME,
        profileName = profileName,
        environment = environment,
        dataSourceId = dataSourceId,
        collectors = emptySet<CollectorFactory>(),
        dispatchers = mutableSetOf(Dispatchers.Collect),
        modules = emptySet<ModuleFactory>()
    )
```

It works perfectly fine on 1.7.0, but fails with 1.7.1 with the following error:

```
None of the following candidates is applicable:
constructor(p0: Application, p1: String, p2: String, p3: Environment, p4: String?, p5: (Mutable)Set<CollectorFactory!>, p6: (Mutable)Set<DispatcherFactory!>, p7: (Mutable)Set<ModuleFactory!>): TealiumConfig
constructor(p0: Application, p1: String, p2: String, p3: Environment, p4: String?, p5: (Mutable)Set<CollectorFactory!>, p6: (Mutable)Set<DispatcherFactory!>): TealiumConfig
constructor(p0: Application, p1: String, p2: String, p3: Environment, p4: String?, p5: (Mutable)Set<CollectorFactory!>): TealiumConfig
constructor(p0: Application, p1: String, p2: String, p3: Environment, p4: String?): TealiumConfig
constructor(p0: Application, p1: String, p2: String, p3: Environment): TealiumConfig
```

If I look at the decompiled class from the library, the signature of the constructor in use seems correct:

```java
public TealiumConfig(
    @NotNull Application application, 
    @NotNull String accountName, 
    @NotNull String profileName, 
    @NotNull Environment environment, 
    @Nullable String dataSourceId, 
    @NotNull Set<CollectorFactory> collectors, 
    @NotNull Set<DispatcherFactory> dispatchers, 
    @NotNull Set<ModuleFactory> modules
) { ... }
```

What's interesting is that if I remove the named parameters from the code, everything works. So this compiles fine:
```kotlin
private fun createConfiguration(
    application: Application,
    profileName: String,
    environment: Environment,
    dataSourceId: String
): TealiumConfig =
    TealiumConfig(
         application,
         ACCOUNT_NAME,
         profileName,
         environment,
         dataSourceId,
         emptySet<CollectorFactory>(),
         mutableSetOf(Dispatchers.Collect),
         emptySet<ModuleFactory>()
    )
```

So something changed in the new version that doesn't allow using Kotlin syntax anymore? Like the named parameters, for instance.

Cheers!

**Comment by craigrouse** [comment]
@vnastasi thanks for reporting this. It does seem a little strange. We'll take a look ASAP. It might be tomorrow before we have an answer for you, but we'll do our best. It sounds suspiciously like a Proguard issue to me, but our Android experts will confirm.

**Comment by emartynov** [comment]
For us it is a bit different - we have compile error with 

```
            Tealium.create(
                name = TealiumConfigurationProvider.INSTANCE_NAME,
                config = TealiumConfigurationProvider().getConfiguration(androidApplication(), BuildConfig.DEBUG)
            ).apply {
                consentManager.enabled = true
                consentManager.userConsentStatus = ConsentStatus.CONSENTED
            }
```

Unresolved function `create`.

**Comment by jameskeith** [comment]
@vnastasi @emartynov - thanks for your patience with this.
Looks like we'd missed the introduction/enabling of R8 FullMode when updating to AGP 8+, so R8 was a little overzealous in removing things when 1.7.1 was published. We've simply disabled that for now whilst we take the time to validate the appropriate additional rules that we need.

We've therefore taken the decision to overwrite 1.7.1 with the corrected version on our maven repository - not something we'd normally do, but seems preferable in this case. 
You'll likely still have the old problematic binary cached on your system though, so we've also republished it as a newer version - 1.7.2 - for an easy update. We've also published an updated version of each of our other binaries too which likely had the same problems.

Please update to 1.7.2 and let us know how you get on.
